### ISSUE TITLE
Can't install on Mac 10.13.1

### ISSUE THREAD

**Issue by asmagen** [arq5x/bedtools2#590]
Hello,

I get the following errors when I make the latest bedtools2 (showing the tail of the output):
StrandQueue.cpp:91:15: error: no member named 'push' in
      'std::__1::priority_queue<Record *, std::__1::vector<const Record *,
      std::__1::allocator<const Record *> >, RecordPtrSortDescFunctor>'
                _queues[2]->push(record);
                ~~~~~~~~~~  ^
StrandQueue.cpp:101:26: error: no member named 'size' in
      'std::__1::priority_queue<Record *, std::__1::vector<const Record *,
      std::__1::allocator<const Record *> >, RecordPtrSortDescFunctor>'
                sumSize += _queues[i]->size();
                           ~~~~~~~~~~  ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[2]: *** [../../../../obj//StrandQueue.o] Error 1
make[1]: *** [Records] Error 2
make: *** [src/utils/FileRecordTools] Error 2

What can I do?

Thanks

**Comment by kthurimella** [comment]
I'm running into a similar issue

**Comment by scnorton** [comment]
Are you trying to install directly from a source clone, or are you using homebrew?

Not sure if this will help, but building from master/HEAD on Mac works in 10.12.6 with the following commands:

```bash
make CXX=clang++
sudo make install CXX=clang++
```

**Comment by arq5x** [comment]
You should also be able compile the latest version in the repo:

```
git clone https://github.com/arq5x/bedtools2
cd bedtools2
make
```

I will be releasing a point release soon that addresses this.
