### ISSUE TITLE
groupby outputs single row 

### ISSUE THREAD

**Issue by dwaggott** [arq5x/bedtools2#418]
I seem to be getting one long row as output from groupby and none of the groupby columns. Is `-g` getting ignored? v2.26.0-5-gcfb2937

Works in bedtools v2.24.0 minus the `-delim`.

[out2.bed](https://gist.github.com/6ff77e796444049eb24572772a384d6a)
`bedtools-dev groupby  -i out2.bed -full -g 1,2,3,4,5 -c 9 -o distinct -delim "|" > out4.bed`

**Comment by charles-plessy** [comment]
I confirm the problem.  Actually, the regression tests in the `test/groupBy` directory fail completely, but unfortunately, they are not run by the `test/test.sh` script.

**Comment by arq5x** [comment]
Sorry for this, I did not detect this regression because the groupby tests were not being run. I am on vacation, but will fix this next week.

**Comment by jstjohn** [comment]
Yeah, I am seeing this as well:

Uniq and wc get 27 rows.
```
/scratch/programs/bedtools2-2.26.0/bin/bedtools intersect -loj  -sortout -a 4FW60.bed -b ../../sql_for_caching_tables/gene_locs_with_3_targets.bed | cut -f1-3 | uniq | wc -l
27
```

Bedtools groupby returns 1 row
```
/scratch/programs/bedtools2-2.26.0/bin/bedtools intersect -loj  -sortout -a 4FW60.bed -b ../../sql_for_caching_tables/gene_locs_with_3_targets.bed | /scratch/programs/bedtools2-2.26.0/bin/bedtools sort | /scratch/programs/bedtools2-2.26.0/bin/bedtools groupby -g 1,2,3 -c 8 -o distinct | wc -l
1
```

Version 2.19 has the correct 27 row return:
```
/scratch/programs/bedtools2-2.26.0/bin/bedtools intersect -loj  -sortout -a 4FW60.bed -b ../../sql_for_caching_tables/gene_locs_with_3_targets.bed | /scratch/programs/bedtools2-2.26.0/bin/bedtools sort | /scratch/programs/bedtools2-2.19.1/bin/bedtools groupby -g 1,2,3 -c 8 -o distinct | wc -l
27
```

**Comment by rmzelle** [comment]
Seeing this as well. Things work correctly with groupBy v1.1.0 (which I think got installed through the [filo](https://github.com/arq5x/filo) package).

**Comment by arq5x** [comment]
Hi all, I see this as well. Scrambling to tie up loose ends before I leave for vacation, but will try to correct this before I leave. Apologies for the regression, the tests for this tools were accidentally disabled and I didn't catch the issue.

**Comment by arq5x** [comment]
This has been addressed in master. The groupby tool in filo is no longer maintained and has been replaced by the groupby tool in bedtools.

**Comment by wangyugui** [comment]
Hi.

The source can't be build on CentOS 7.2

```
groupBy.cpp: In member function ‘virtual void GroupBy::processHits(RecordOutputMgr*, RecordKeyVector&)’:
groupBy.cpp:85:28: error: invalid conversion from ‘RecordKeyVector::elemType {aka const Record*}’ to ‘Record*’ [-fpermissive]
  Record *rec = hits.getKey();
                            ^
groupBy.cpp: In member function ‘virtual void GroupBy::cleanupHits(RecordKeyVector&)’:
groupBy.cpp:107:2: error: ‘iterator_type’ is not a member of ‘RecordKeyVector’
  RecordKeyVector::iterator_type iter = hits.begin();
  ^
groupBy.cpp:107:33: error: expected ‘;’ before ‘iter’
  RecordKeyVector::iterator_type iter = hits.begin();
                                 ^
groupBy.cpp:108:9: error: ‘iter’ was not declared in this scope
  for (; iter != hits.end(); iter = hits.next())
         ^
make[1]: *** [../../obj//groupBy.o] Error 1
make: *** [src/groupBy] Error 2
```
